site_name: Azure-OSS
site_description: Documentation for Azure-OSS

repo_name: Azure-OSS
repo_url: https://github.com/Azure-OSS
edit_uri: https://github.com/Azure-OSS/azure-oss.github.io/edit/main/docs/

theme:
  name: material
  font:
    text: 'Nunito'
    code: 'Fira Code'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: images/favicon.ico
  logo: https://cdnlogo.com/logos/a/12/azure.svg
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - content.action.edit
    - navigation.instant

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Azure-OSS
      name: Azure-OSS repository
    - icon: fontawesome/regular/file-lines
      link: https://github.com/Azure-OSS/azure-oss.github.io
      name: Docs repository

plugins:
  - search: { }

nav:
  - index.md
  - 'Storage':
      - storage/blob.md

markdown_extensions:
  - admonition: { }
  - meta: { }
  - toc:
      permalink: '#'
  - pymdownx.details: { }
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences: { }
  - pymdownx.keys: { }

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js
  - javascripts/highlight.js

# Themes can be found here: <https://github.com/highlightjs/highlight.js/tree/master/src/styles>
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/atom-one-dark-reasonable.min.css
